# -*- coding: utf-8 -*-
"""Sobreposição da pose e do segmento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bg92UUHvQWI9RhyUKZ1m5REclY30xDuf
"""

from google.colab import drive
drive.mount('/content/gdrive')

#Esse código vai sobrepor todas as imagens de teste do conjunto de dados e criar uma imagem salvando o resultado obtido.

import cv2
import os
import matplotlib.pyplot as plt


# Definindo os diretórios das imagens e de salvamento
pasta_pred_segmentos = '/content/gdrive/MyDrive/MESTRADO/Disciplinas/Visão Computacional/Segmentação com SAM2/predict'
pasta_pred_keypoints = '/content/gdrive/MyDrive/MESTRADO/Disciplinas/Visão Computacional/Estimativa de pose com yolo 11/Testes com yolo11/runs/pose/extra_large'
pasta_resultados = '/content/resultados_sobreposicao'

# Criar a pasta de resultados se ela não existir
if not os.path.exists(pasta_resultados):
    os.makedirs(pasta_resultados)

# Função para sobrepor duas imagens
def sobrepor_imagens(segmentos_path, keypoints_path):
    # Carregar as imagens
    segmentos = cv2.imread(segmentos_path, 1)
    keypoints = cv2.imread(keypoints_path, 1)

    if segmentos is None or keypoints is None:
        print(f"Erro ao carregar {segmentos_path} ou {keypoints_path}")
        return None

    # Sobrepor as imagens com transparência
    img_sobreposta = cv2.addWeighted(segmentos, 0.4, keypoints, 0.6, 0)
    return img_sobreposta

# Caminha pelas imagens nas pastas e realiza a sobreposição
for img_nome in os.listdir(pasta_pred_segmentos):
    # Ignora a pasta de labels
    if img_nome.endswith('.jpg') and not img_nome.startswith('labels'):
        # Caminho completo das imagens
        segmentos_path = os.path.join(pasta_pred_segmentos, img_nome)
        keypoints_path = os.path.join(pasta_pred_keypoints, img_nome)

        # Verifica se a imagem correspondente existe na outra pasta
        if os.path.exists(keypoints_path):
            img_sobreposta = sobrepor_imagens(segmentos_path, keypoints_path)

            if img_sobreposta is not None:
                # Caminho para salvar a imagem sobreposta
                caminho_salvar = os.path.join(pasta_resultados, img_nome)

                # Salva a imagem sobreposta
                cv2.imwrite(caminho_salvar, img_sobreposta)
                print(f"Imagem sobreposta salva em: {caminho_salvar}")
        else:
            print(f"Imagem correspondente não encontrada para {img_nome}")

imagens_resultados = '/content/resultados_sobreposicao'

#Envia as imagens sobrepostas para o drive
!cp -R {imagens_resultados} /content/gdrive/MyDrive/MESTRADO/Disciplinas/Visão\ Computacional/Sobreposição\ imagens\ pose\ e\ segmento